services:
  app:
    build: ./
    environment:
      PORT: 4200
      NODE_ENV: development
      DATABASE_URL: postgresql://user:password@localhost/db:5432
    ports:
      - 4200:4200

  db:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
