services:
  app:
    build: ./
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://user:password@localhost/db:5432
    ports:
      - 8080:8080

  db:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
